In [1]:
import pandas as pd

# Чтение Excel файла
df = pd.read_excel('experiments/total_perceptron_tests/data/Concrete_Data.xls')

# Запись в CSV файл
df.to_csv('experiments/total_perceptron_tests/data/concrete_data.csv', index=False)

In [10]:
import pickle

with open('700-data.pkl', 'rb') as file:
    f = pickle.load(file)

In [2]:
import json

with open('test-data.txt', 'w') as file:
    json.dump(f, file, indent=4, sort_keys=True)

TypeError: Object of type Parameter is not JSON serializable

In [11]:
f

{'layer.0': {'weights': Parameter containing:
  tensor([[ 0.0199, -0.0620,  0.0781,  ...,  0.1752,  0.0696,  0.0540],
          [ 0.0726,  0.0096, -0.1314,  ..., -0.0079,  0.0586, -0.0535],
          [-0.0691, -0.0035,  0.0634,  ...,  0.0205,  0.0121, -0.0862],
          ...,
          [-0.0627, -0.0088,  0.0616,  ..., -0.1539, -0.1223, -0.0130],
          [-0.0790,  0.0054,  0.0863,  ..., -0.1503, -0.1365,  0.0142],
          [ 0.0227,  0.0865,  0.0844,  ...,  0.0971,  0.0065,  0.0113]],
         device='cuda:0', requires_grad=True),
  'weights_rank': tensor(64, device='cuda:0'),
  'weights_spectral': {'mean': -0.0005502321873791516,
   'std': 0.10704716295003891,
   'min': -0.5232753157615662,
   'max': 0.3699827194213867,
   'skewness': -0.05650862089106667,
   'kurtosis': 0.28499655838002935,
   'histogram': {'bins': [-0.5232753157615662,
     -0.47861242294311523,
     -0.4339495003223419,
     -0.389286607503891,
     -0.34462371468544006,
     -0.29996079206466675,
     -0.25529

In [9]:
import torch
from experiments.total_perceptron_tests.models import create_model
from experiments.total_perceptron_tests.datasets import prepare_wine_data
from hessian.layer_wise_hessian import compute_local_hessians_for_chunks

X_train, X_test, y_train, y_test = prepare_wine_data()
model = create_model("Wine", "sure")
compute_local_hessians_for_chunks(model, torch.from_numpy(X_test[2]).float())

OrderedDict([(0,
              tensor([[-0., 0., 0.,  ..., 0., 0., 0.],
                      [-0., 0., 0.,  ..., 0., 0., 0.],
                      [-0., 0., 0.,  ..., 0., 0., 0.],
                      ...,
                      [-0., 0., 0.,  ..., 0., 0., 0.],
                      [-0., 0., 0.,  ..., 0., 0., 0.],
                      [-0., 0., 0.,  ..., 0., 0., 0.]])),
             (1,
              tensor([[0., 0., 0.,  ..., 0., 0., 0.],
                      [0., 0., 0.,  ..., 0., 0., 0.],
                      [0., 0., 0.,  ..., 0., 0., 0.],
                      ...,
                      [0., 0., 0.,  ..., 0., 0., 0.],
                      [0., 0., 0.,  ..., 0., 0., 0.],
                      [0., 0., 0.,  ..., 0., 0., 0.]])),
             (2,
              tensor([[0., 0., 0.,  ..., 0., 0., 0.],
                      [0., 0., 0.,  ..., 0., 0., 0.],
                      [0., 0., 0.,  ..., 0., 0., 0.],
                      ...,
                      [0., 0., 0.,  ..., 0., 0